export interface Question {
  id: number
  subject: string
  question: string
  options: string[]
  correct: number
}

// 45 Questões de Linguagens
export const linguagensQuestions: Question[] = [
  {
    id: 1,
    subject: "Interpretação de Texto",
    question:
      "Leia o trecho: 'A tecnologia digital transformou não apenas a forma como nos comunicamos, mas também como construímos relações sociais.' O autor sugere que:",
    options: [
      "A tecnologia afeta superficialmente as relações",
      "Apenas a comunicação foi modificada pela tecnologia",
      "Houve uma transformação profunda nas interações sociais",
      "As relações sociais não foram impactadas",
      "A comunicação permaneceu inalterada",
    ],
    correct: 2,
  },
  {
    id: 2,
    subject: "Figuras de Linguagem",
    question: "Em 'O tempo voa quando estamos felizes', identifica-se a figura de linguagem:",
    options: ["Metáfora", "Hipérbole", "Eufemismo", "Metonímia", "Personificação"],
    correct: 4,
  },
  {
    id: 3,
    subject: "Literatura Brasileira",
    question: "Machado de Assis, em 'Memórias Póstumas de Brás Cubas', inaugura no Brasil:",
    options: ["O Romantismo", "O Realismo", "O Modernismo", "O Naturalismo", "O Parnasianismo"],
    correct: 1,
  },
  {
    id: 4,
    subject: "Gramática - Crase",
    question: "A crase é obrigatória em:",
    options: [
      "Vou a festa de Maria",
      "Refiro-me a pessoas competentes",
      "Cheguei a casa cedo",
      "Vou à praia amanhã",
      "Estou disposto a colaborar",
    ],
    correct: 3,
  },
  {
    id: 5,
    subject: "Modernismo",
    question: "O Modernismo brasileiro teve como marco inicial:",
    options: [
      "A Semana de Arte Moderna de 1922",
      "A publicação de Dom Casmurro",
      "A chegada da corte portuguesa",
      "O Manifesto Antropofágico",
      "A criação da ABL",
    ],
    correct: 0,
  },
  {
    id: 6,
    subject: "Concordância Verbal",
    question: "Assinale a alternativa com concordância correta:",
    options: [
      "Houveram muitos problemas",
      "Fazem dois anos que não o vejo",
      "Deve haver soluções para isso",
      "Haviam muitas pessoas",
      "Podem haver dúvidas",
    ],
    correct: 2,
  },
  {
    id: 7,
    subject: "Funções da Linguagem",
    question: "Em 'Alô! Está me ouvindo?', predomina a função:",
    options: ["Emotiva", "Conativa", "Fática", "Metalinguística", "Referencial"],
    correct: 2,
  },
  {
    id: 8,
    subject: "Romantismo",
    question: "São características do Romantismo brasileiro:",
    options: [
      "Objetividade e racionalismo",
      "Nacionalismo e idealização",
      "Linguagem rebuscada e mitologia",
      "Análise psicológica e crítica social",
      "Experimentação formal",
    ],
    correct: 1,
  },
  {
    id: 9,
    subject: "Regência Verbal",
    question: "O verbo 'assistir' no sentido de 'ver' exige:",
    options: [
      "Objeto direto",
      "Objeto indireto com 'a'",
      "Objeto direto preposicionado",
      "Predicativo do sujeito",
      "Complemento nominal",
    ],
    correct: 1,
  },
  {
    id: 10,
    subject: "Gêneros Textuais",
    question: "O texto dissertativo-argumentativo caracteriza-se por:",
    options: [
      "Narrar fatos em sequência",
      "Descrever características",
      "Defender um ponto de vista com argumentos",
      "Dar instruções",
      "Relatar experiências pessoais",
    ],
    correct: 2,
  },
  {
    id: 11,
    subject: "Coesão Textual",
    question: "Os conectivos 'porém', 'todavia' e 'contudo' expressam:",
    options: ["Adição", "Conclusão", "Oposição", "Causa", "Tempo"],
    correct: 2,
  },
  {
    id: 12,
    subject: "Variação Linguística",
    question: "A norma culta da língua portuguesa é:",
    options: [
      "A única forma correta de falar",
      "Uma variedade de prestígio social",
      "Usada apenas na escrita",
      "Igual em todas as regiões",
      "A língua falada no dia a dia",
    ],
    correct: 1,
  },
  {
    id: 13,
    subject: "Colocação Pronominal",
    question: "Em 'Nunca me disseram a verdade', ocorre:",
    options: ["Próclise", "Ênclise", "Mesóclise", "Anáfora", "Catáfora"],
    correct: 0,
  },
  {
    id: 14,
    subject: "Parnasianismo",
    question: "O Parnasianismo brasileiro valorizava:",
    options: [
      "A emoção e subjetividade",
      "A perfeição formal e objetividade",
      "A crítica social",
      "O indianismo",
      "A experimentação linguística",
    ],
    correct: 1,
  },
  {
    id: 15,
    subject: "Orações Subordinadas",
    question: "Em 'É necessário que todos participem', a oração destacada é:",
    options: [
      "Subordinada substantiva objetiva direta",
      "Subordinada substantiva subjetiva",
      "Subordinada adjetiva restritiva",
      "Subordinada adverbial final",
      "Coordenada sindética",
    ],
    correct: 1,
  },
  {
    id: 16,
    subject: "Ambiguidade",
    question: "A frase 'O professor falou com o aluno no corredor' apresenta ambiguidade porque:",
    options: [
      "Não sabemos quem estava no corredor",
      "Falta concordância verbal",
      "Há erro de regência",
      "O sujeito está oculto",
      "Falta pontuação",
    ],
    correct: 0,
  },
  {
    id: 17,
    subject: "Semântica",
    question: "As palavras 'manga' (fruta) e 'manga' (roupa) são exemplos de:",
    options: ["Sinônimos", "Antônimos", "Homônimos", "Parônimos", "Hiperônimos"],
    correct: 2,
  },
  {
    id: 18,
    subject: "Pronomes",
    question: "Em 'Isso não me interessa', o pronome 'isso' é:",
    options: ["Pessoal", "Possessivo", "Demonstrativo", "Indefinido", "Relativo"],
    correct: 2,
  },
  {
    id: 19,
    subject: "Vozes Verbais",
    question: "A frase 'A carta foi escrita por mim' está na voz:",
    options: ["Ativa", "Passiva analítica", "Passiva sintética", "Reflexiva", "Recíproca"],
    correct: 1,
  },
  {
    id: 20,
    subject: "Conjunções",
    question: "A conjunção 'embora' expressa:",
    options: ["Causa", "Concessão", "Condição", "Conformidade", "Finalidade"],
    correct: 1,
  },
  {
    id: 21,
    subject: "Acentuação",
    question: "São acentuadas pela mesma regra:",
    options: ["Água, saúde, país", "Até, café, você", "Fácil, útil, móvel", "Alguém, também, armazém", "Pó, só, dó"],
    correct: 3,
  },
  {
    id: 22,
    subject: "Classes Gramaticais",
    question: "Na frase 'Compramos pouco arroz', a palavra 'pouco' é:",
    options: ["Adjetivo", "Advérbio", "Pronome indefinido", "Substantivo", "Numeral"],
    correct: 2,
  },
  {
    id: 23,
    subject: "Literatura - Barroco",
    question: "Gregório de Matos ficou conhecido como:",
    options: [
      "O poeta dos escravos",
      "O poeta indianista",
      "Boca do Inferno",
      "O bruxo do Cosme Velho",
      "O poeta da morte",
    ],
    correct: 2,
  },
  {
    id: 24,
    subject: "Predicação Verbal",
    question: "O verbo 'parecer' em 'Maria parece feliz' é:",
    options: ["Transitivo direto", "Transitivo indireto", "De ligação", "Intransitivo", "Bitransitivo"],
    correct: 2,
  },
  {
    id: 25,
    subject: "Aposto e Vocativo",
    question: "Em 'Maria, venha aqui!', o termo destacado é:",
    options: ["Sujeito", "Aposto", "Vocativo", "Predicativo", "Objeto direto"],
    correct: 2,
  },
  {
    id: 26,
    subject: "Pontuação",
    question: "A vírgula é obrigatória em:",
    options: [
      "O menino que estuda passa",
      "Ele chegou, e saiu rapidamente",
      "João estuda matemática",
      "Gosto de estudar português",
      "Maria comprou livros",
    ],
    correct: 1,
  },
  {
    id: 27,
    subject: "Arcadismo",
    question: "O Arcadismo no Brasil teve como característica:",
    options: [
      "Culto ao teocentrismo",
      "Valorização do urbano",
      "Ideal de vida simples",
      "Nacionalismo exacerbado",
      "Liberdade formal",
    ],
    correct: 2,
  },
  {
    id: 28,
    subject: "Análise Sintática",
    question: "Em 'O professor entregou as provas aos alunos', há:",
    options: ["VTD + OD", "VTI + OI", "VTDI + OD + OI", "VL + PS", "VI + AA"],
    correct: 2,
  },
  {
    id: 29,
    subject: "Formação de Palavras",
    question: "A palavra 'infeliz' foi formada por:",
    options: ["Derivação sufixal", "Derivação prefixal", "Composição", "Hibridismo", "Onomatopeia"],
    correct: 1,
  },
  {
    id: 30,
    subject: "Preposições",
    question: "A preposição 'com' indica:",
    options: ["Apenas companhia", "Apenas modo", "Companhia, modo ou instrumento", "Apenas lugar", "Apenas tempo"],
    correct: 2,
  },
  {
    id: 31,
    subject: "Literatura Contemporânea",
    question: "Clarice Lispector destaca-se por:",
    options: ["Poesia épica", "Prosa introspectiva", "Teatro político", "Crônicas humorísticas", "Poesia concreta"],
    correct: 1,
  },
  {
    id: 32,
    subject: "Sintaxe de Concordância",
    question: "'A maioria dos alunos passaram' está:",
    options: [
      "Correta pela concordância ideológica",
      "Incorreta sempre",
      "Correta apenas no plural",
      "Correta apenas no singular",
      "Ambígua",
    ],
    correct: 0,
  },
  {
    id: 33,
    subject: "Interjeição",
    question: "'Ai! Que dor!' A interjeição expressa:",
    options: ["Alegria", "Dor", "Surpresa", "Desejo", "Chamamento"],
    correct: 1,
  },
  {
    id: 34,
    subject: "Tipos de Sujeito",
    question: "Em 'Choveu muito ontem', o sujeito é:",
    options: ["Simples", "Composto", "Indeterminado", "Inexistente", "Oculto"],
    correct: 3,
  },
  {
    id: 35,
    subject: "Intertextualidade",
    question: "Quando um texto faz referência a outro texto, ocorre:",
    options: ["Coesão", "Coerência", "Intertextualidade", "Ambiguidade", "Redundância"],
    correct: 2,
  },
  {
    id: 36,
    subject: "Naturalismo",
    question: "O Naturalismo brasileiro caracteriza-se por:",
    options: ["Idealização romântica", "Determinismo científico", "Arte pela arte", "Nacionalismo", "Subjetivismo"],
    correct: 1,
  },
  {
    id: 37,
    subject: "Complemento Nominal",
    question: "Complemento nominal completa o sentido de:",
    options: [
      "Apenas verbos",
      "Substantivos, adjetivos e advérbios",
      "Apenas substantivos",
      "Apenas pronomes",
      "Apenas verbos transitivos",
    ],
    correct: 1,
  },
  {
    id: 38,
    subject: "Advérbios",
    question: "'Aqui' é advérbio de:",
    options: ["Tempo", "Modo", "Lugar", "Intensidade", "Afirmação"],
    correct: 2,
  },
  {
    id: 39,
    subject: "Artigo",
    question: "O uso do artigo definido em 'O Brasil é grande' indica:",
    options: ["Indefinição", "Particularização", "Generalização", "Familiaridade", "Ambiguidade"],
    correct: 3,
  },
  {
    id: 40,
    subject: "Transitividade Verbal",
    question: "O verbo 'necessitar' é:",
    options: ["Intransitivo", "Transitivo direto", "Transitivo indireto", "De ligação", "Impessoal"],
    correct: 2,
  },
  {
    id: 41,
    subject: "Literatura - Simbolismo",
    question: "Cruz e Sousa foi um importante poeta:",
    options: ["Romântico", "Parnasiano", "Simbolista", "Modernista", "Realista"],
    correct: 2,
  },
  {
    id: 42,
    subject: "Período Composto",
    question: "'Estudei muito, mas não passei' é um período:",
    options: ["Simples", "Composto por coordenação", "Composto por subordinação", "Composto misto", "Nominal"],
    correct: 1,
  },
  {
    id: 43,
    subject: "Numeral",
    question: "'Dobro' é numeral:",
    options: ["Cardinal", "Ordinal", "Multiplicativo", "Fracionário", "Coletivo"],
    correct: 2,
  },
  {
    id: 44,
    subject: "Termos Acessórios",
    question: "Em 'O livro novo está aqui', 'novo' é:",
    options: ["Predicativo", "Adjunto adnominal", "Complemento nominal", "Aposto", "Objeto direto"],
    correct: 1,
  },
  {
    id: 45,
    subject: "Conotação e Denotação",
    question: "'Aquele homem tem um coração de pedra' usa linguagem:",
    options: ["Denotativa", "Conotativa", "Técnica", "Formal", "Regional"],
    correct: 1,
  },
]

// 45 Questões de Matemática
export const matematicaQuestions: Question[] = [
  {
    id: 1,
    subject: "Equação do 1º Grau",
    question: "Resolvendo a equação 3x + 7 = 22, o valor de x é:",
    options: ["3", "5", "7", "9", "11"],
    correct: 1,
  },
  {
    id: 2,
    subject: "Porcentagem",
    question: "Uma mercadoria que custava R$ 200,00 teve um desconto de 15%. Seu novo preço é:",
    options: ["R$ 150,00", "R$ 170,00", "R$ 185,00", "R$ 190,00", "R$ 195,00"],
    correct: 1,
  },
  {
    id: 3,
    subject: "Geometria - Triângulos",
    question: "Em um triângulo retângulo com catetos 3 e 4, a hipotenusa mede:",
    options: ["5", "6", "7", "8", "9"],
    correct: 0,
  },
  {
    id: 4,
    subject: "Função do 1º Grau",
    question: "Dada f(x) = 2x + 3, o valor de f(5) é:",
    options: ["8", "10", "11", "13", "15"],
    correct: 3,
  },
  {
    id: 5,
    subject: "Razão e Proporção",
    question: "Se 5/x = 15/9, então x vale:",
    options: ["2", "3", "4", "5", "6"],
    correct: 1,
  },
  {
    id: 6,
    subject: "Equação do 2º Grau",
    question: "As raízes da equação x² - 5x + 6 = 0 são:",
    options: ["1 e 6", "2 e 3", "-2 e -3", "1 e 5", "0 e 6"],
    correct: 1,
  },
  {
    id: 7,
    subject: "Geometria - Áreas",
    question: "A área de um quadrado de lado 8 cm é:",
    options: ["16 cm²", "32 cm²", "48 cm²", "64 cm²", "72 cm²"],
    correct: 3,
  },
  {
    id: 8,
    subject: "Juros Simples",
    question: "Um capital de R$ 1.000 aplicado a 10% ao ano por 2 anos rende:",
    options: ["R$ 100", "R$ 150", "R$ 200", "R$ 250", "R$ 300"],
    correct: 2,
  },
  {
    id: 9,
    subject: "Estatística - Média",
    question: "A média aritmética de 4, 8, 10 e 14 é:",
    options: ["7", "8", "9", "10", "11"],
    correct: 2,
  },
  {
    id: 10,
    subject: "Probabilidade",
    question: "Ao lançar um dado, a probabilidade de sair um número par é:",
    options: ["1/6", "1/3", "1/2", "2/3", "5/6"],
    correct: 2,
  },
  {
    id: 11,
    subject: "Geometria - Perímetro",
    question: "O perímetro de um retângulo de lados 5 e 8 é:",
    options: ["13", "20", "26", "30", "40"],
    correct: 2,
  },
  {
    id: 12,
    subject: "Regra de Três",
    question: "Se 3 operários fazem um trabalho em 12 dias, 6 operários farão em:",
    options: ["3 dias", "4 dias", "6 dias", "8 dias", "9 dias"],
    correct: 2,
  },
  {
    id: 13,
    subject: "Potenciação",
    question: "O valor de 2⁵ é:",
    options: ["10", "16", "25", "32", "64"],
    correct: 3,
  },
  {
    id: 14,
    subject: "Função do 2º Grau",
    question: "O vértice da parábola y = x² - 4x + 3 tem coordenada x igual a:",
    options: ["1", "2", "3", "4", "5"],
    correct: 1,
  },
  {
    id: 15,
    subject: "Geometria Espacial",
    question: "O volume de um cubo de aresta 3 é:",
    options: ["9", "18", "27", "36", "81"],
    correct: 2,
  },
  {
    id: 16,
    subject: "Progressão Aritmética",
    question: "Na PA (2, 5, 8, 11, ...), o 10º termo é:",
    options: ["26", "29", "32", "35", "38"],
    correct: 1,
  },
  {
    id: 17,
    subject: "Radiciação",
    question: "A √144 é igual a:",
    options: ["10", "11", "12", "13", "14"],
    correct: 2,
  },
  {
    id: 18,
    subject: "Trigonometria",
    question: "O seno de 30° é:",
    options: ["0", "1/2", "√2/2", "√3/2", "1"],
    correct: 1,
  },
  {
    id: 19,
    subject: "Sistema Linear",
    question: "No sistema {x + y = 10, x - y = 2}, o valor de x é:",
    options: ["4", "5", "6", "7", "8"],
    correct: 2,
  },
  {
    id: 20,
    subject: "Análise Combinatória",
    question: "O número de anagramas da palavra 'SOL' é:",
    options: ["3", "4", "5", "6", "7"],
    correct: 3,
  },
  {
    id: 21,
    subject: "Logaritmo",
    question: "O valor de log₂8 é:",
    options: ["1", "2", "3", "4", "5"],
    correct: 2,
  },
  {
    id: 22,
    subject: "Geometria - Círculo",
    question: "A área de um círculo de raio 5 é (use π ≈ 3):",
    options: ["50", "75", "100", "125", "150"],
    correct: 1,
  },
  {
    id: 23,
    subject: "Notação Científica",
    question: "O número 0,00035 em notação científica é:",
    options: ["3,5 × 10⁻⁴", "3,5 × 10⁻³", "35 × 10⁻⁵", "3,5 × 10⁻⁵", "0,35 × 10⁻³"],
    correct: 0,
  },
  {
    id: 24,
    subject: "Matriz",
    question: "Uma matriz 3×4 possui quantos elementos?",
    options: ["7", "10", "12", "15", "16"],
    correct: 2,
  },
  {
    id: 25,
    subject: "Função Exponencial",
    question: "Se 2ˣ = 16, então x vale:",
    options: ["2", "3", "4", "5", "6"],
    correct: 2,
  },
  {
    id: 26,
    subject: "Geometria - Ângulos",
    question: "Dois ângulos complementares somam:",
    options: ["45°", "90°", "180°", "270°", "360°"],
    correct: 1,
  },
  {
    id: 27,
    subject: "Progressão Geométrica",
    question: "Na PG (2, 6, 18, ...), a razão é:",
    options: ["2", "3", "4", "6", "9"],
    correct: 1,
  },
  {
    id: 28,
    subject: "Equação Irracional",
    question: "A solução de √(x+1) = 3 é:",
    options: ["6", "7", "8", "9", "10"],
    correct: 2,
  },
  {
    id: 29,
    subject: "Geometria - Polígonos",
    question: "A soma dos ângulos internos de um pentágono é:",
    options: ["360°", "540°", "720°", "900°", "1080°"],
    correct: 1,
  },
  {
    id: 30,
    subject: "Fração",
    question: "A fração 3/4 + 1/2 é igual a:",
    options: ["4/6", "5/4", "7/8", "1", "5/6"],
    correct: 1,
  },
  {
    id: 31,
    subject: "Módulo",
    question: "O valor de |−7| + |3| é:",
    options: ["4", "−4", "10", "−10", "7"],
    correct: 2,
  },
  {
    id: 32,
    subject: "Inequação",
    question: "A solução de 2x - 4 > 6 é:",
    options: ["x > 3", "x > 5", "x < 3", "x < 5", "x = 5"],
    correct: 1,
  },
  {
    id: 33,
    subject: "Geometria Analítica",
    question: "A distância entre os pontos (0,0) e (3,4) é:",
    options: ["3", "4", "5", "6", "7"],
    correct: 2,
  },
  {
    id: 34,
    subject: "Binômio de Newton",
    question: "(a + b)² é igual a:",
    options: ["a² + b²", "a² + 2ab + b²", "a² - 2ab + b²", "2a² + 2b²", "a² + ab + b²"],
    correct: 1,
  },
  {
    id: 35,
    subject: "Polinômios",
    question: "O grau do polinômio 3x⁴ + 2x² - 5 é:",
    options: ["2", "3", "4", "5", "6"],
    correct: 2,
  },
  {
    id: 36,
    subject: "Estatística - Mediana",
    question: "A mediana de {2, 5, 8, 10, 15} é:",
    options: ["5", "7", "8", "10", "15"],
    correct: 2,
  },
  {
    id: 37,
    subject: "Ângulos em Triângulos",
    question: "Em um triângulo, se dois ângulos medem 40° e 60°, o terceiro mede:",
    options: ["60°", "70°", "80°", "90°", "100°"],
    correct: 2,
  },
  {
    id: 38,
    subject: "Números Complexos",
    question: "A parte imaginária de 3 + 4i é:",
    options: ["3", "4", "3i", "4i", "7"],
    correct: 1,
  },
  {
    id: 39,
    subject: "Escala",
    question: "Em um mapa de escala 1:100.000, 2 cm representam:",
    options: ["2 km", "20 km", "200 km", "2000 km", "20.000 km"],
    correct: 0,
  },
  {
    id: 40,
    subject: "Função Inversa",
    question: "A inversa de f(x) = 2x + 4 é:",
    options: ["(x - 4)/2", "(x + 4)/2", "2x - 4", "x/2 - 4", "2(x - 4)"],
    correct: 0,
  },
  {
    id: 41,
    subject: "Cone",
    question: "Um cone tem raio da base 3 e altura 4. Sua geratriz mede:",
    options: ["3", "4", "5", "6", "7"],
    correct: 2,
  },
  {
    id: 42,
    subject: "Lógica",
    question: "A negação de 'Todos os gatos são pretos' é:",
    options: [
      "Nenhum gato é preto",
      "Alguns gatos não são pretos",
      "Todos os gatos não são pretos",
      "Nenhum gato existe",
      "Alguns gatos são pretos",
    ],
    correct: 1,
  },
  {
    id: 43,
    subject: "Múltiplos e Divisores",
    question: "O MMC de 12 e 18 é:",
    options: ["6", "18", "36", "54", "72"],
    correct: 2,
  },
  {
    id: 44,
    subject: "Cilindro",
    question: "A área lateral de um cilindro com raio 2 e altura 5 é (use π = 3):",
    options: ["30", "40", "50", "60", "70"],
    correct: 3,
  },
  {
    id: 45,
    subject: "Desigualdade Triangular",
    question: "Pode formar um triângulo os lados:",
    options: ["2, 3, 10", "4, 5, 9", "1, 2, 4", "5, 7, 15", "3, 4, 5"],
    correct: 4,
  },
]

// 45 Questões de Ciências Humanas
export const humanasQuestions: Question[] = [
  {
    id: 1,
    subject: "História do Brasil",
    question: "A independência do Brasil foi proclamada em:",
    options: ["1500", "1789", "1822", "1889", "1922"],
    correct: 2,
  },
  {
    id: 2,
    subject: "Geografia - Clima",
    question: "O clima predominante no Brasil é:",
    options: ["Temperado", "Tropical", "Polar", "Desértico", "Mediterrâneo"],
    correct: 1,
  },
  {
    id: 3,
    subject: "Filosofia",
    question: "Sócrates afirmava que:",
    options: [
      "Sei que nada sei",
      "Penso, logo existo",
      "O homem é a medida de todas as coisas",
      "Tudo flui",
      "O ser é, o não-ser não é",
    ],
    correct: 0,
  },
  {
    id: 4,
    subject: "Sociologia",
    question: "O conceito de 'fato social' foi desenvolvido por:",
    options: ["Karl Marx", "Max Weber", "Émile Durkheim", "Auguste Comte", "Michel Foucault"],
    correct: 2,
  },
  {
    id: 5,
    subject: "História Geral",
    question: "A Revolução Francesa ocorreu em:",
    options: ["1689", "1776", "1789", "1848", "1917"],
    correct: 2,
  },
  {
    id: 6,
    subject: "Geografia - Hidrografia",
    question: "O maior rio do mundo em volume de água é:",
    options: ["Nilo", "Mississipi", "Yangtzé", "Amazonas", "Ganges"],
    correct: 3,
  },
  {
    id: 7,
    subject: "História - Era Vargas",
    question: "Getúlio Vargas governou o Brasil durante:",
    options: ["1889-1930", "1930-1945", "1945-1964", "1964-1985", "1985-2000"],
    correct: 1,
  },
  {
    id: 8,
    subject: "Geografia - Relevo",
    question: "O ponto mais alto do Brasil é:",
    options: ["Pico da Neblina", "Pico da Bandeira", "Serra do Mar", "Chapada Diamantina", "Serra da Mantiqueira"],
    correct: 0,
  },
  {
    id: 9,
    subject: "Filosofia - Platão",
    question: "A teoria das ideias foi desenvolvida por:",
    options: ["Sócrates", "Platão", "Aristóteles", "Tales", "Heráclito"],
    correct: 1,
  },
  {
    id: 10,
    subject: "Sociologia - Classes Sociais",
    question: "Para Marx, a luta de classes é entre:",
    options: [
      "Ricos e pobres",
      "Burguesia e proletariado",
      "Nobres e servos",
      "Senhores e escravos",
      "Patrões e empregados",
    ],
    correct: 1,
  },
  {
    id: 11,
    subject: "História - Ditadura Militar",
    question: "A ditadura militar no Brasil durou de:",
    options: ["1954-1964", "1964-1985", "1985-2000", "1930-1945", "1945-1964"],
    correct: 1,
  },
  {
    id: 12,
    subject: "Geografia - População",
    question: "A população brasileira concentra-se principalmente:",
    options: ["No interior", "Na Amazônia", "No litoral", "No Centro-Oeste", "Uniformemente"],
    correct: 2,
  },
  {
    id: 13,
    subject: "Filosofia Moderna",
    question: "'Penso, logo existo' foi dito por:",
    options: ["Kant", "Descartes", "Hegel", "Nietzsche", "Sartre"],
    correct: 1,
  },
  {
    id: 14,
    subject: "Sociologia - Cultura",
    question: "Etnocentrismo é:",
    options: [
      "Estudar outras culturas",
      "Julgar outras culturas pela nossa",
      "Respeitar todas as culturas",
      "Misturar culturas",
      "Criar uma cultura nova",
    ],
    correct: 1,
  },
  {
    id: 15,
    subject: "História - Escravidão",
    question: "A Lei Áurea foi assinada em:",
    options: ["1850", "1871", "1885", "1888", "1889"],
    correct: 3,
  },
  {
    id: 16,
    subject: "Geografia - Biomas",
    question: "O Cerrado localiza-se principalmente:",
    options: ["No Sul", "No Nordeste", "No Norte", "No Centro-Oeste", "No Sudeste"],
    correct: 3,
  },
  {
    id: 17,
    subject: "História - Primeira Guerra",
    question: "A Primeira Guerra Mundial ocorreu entre:",
    options: ["1900-1905", "1914-1918", "1939-1945", "1950-1953", "1960-1975"],
    correct: 1,
  },
  {
    id: 18,
    subject: "Geografia - Urbanização",
    question: "O êxodo rural é:",
    options: [
      "Migração do campo para a cidade",
      "Migração da cidade para o campo",
      "Migração internacional",
      "Crescimento da população rural",
      "Diminuição da população urbana",
    ],
    correct: 0,
  },
  {
    id: 19,
    subject: "Filosofia - Iluminismo",
    question: "O Iluminismo valorizava:",
    options: ["A fé", "A razão", "A tradição", "A monarquia", "O misticismo"],
    correct: 1,
  },
  {
    id: 20,
    subject: "Sociologia - Estratificação",
    question: "Mobilidade social vertical ascendente significa:",
    options: [
      "Mudar de região",
      "Subir de classe social",
      "Descer de classe social",
      "Mudar de profissão",
      "Mudar de geração",
    ],
    correct: 1,
  },
  {
    id: 21,
    subject: "História - República",
    question: "A República foi proclamada no Brasil em:",
    options: ["1822", "1850", "1888", "1889", "1891"],
    correct: 3,
  },
  {
    id: 22,
    subject: "Geografia - Agricultura",
    question: "Agricultura extensiva caracteriza-se por:",
    options: [
      "Uso intensivo de tecnologia",
      "Pequenas propriedades",
      "Grande uso de mão de obra",
      "Baixa produtividade por área",
      "Produção orgânica",
    ],
    correct: 3,
  },
  {
    id: 23,
    subject: "Filosofia - Aristóteles",
    question: "Para Aristóteles, o ser humano é:",
    options: ["Animal racional", "Animal político", "Ser pensante", "Criatura divina", "Produto social"],
    correct: 1,
  },
  {
    id: 24,
    subject: "Sociologia - Instituições",
    question: "A família é uma instituição:",
    options: ["Econômica", "Social", "Política", "Religiosa", "Educacional"],
    correct: 1,
  },
  {
    id: 25,
    subject: "História - Colonização",
    question: "O Brasil foi colonizado por:",
    options: ["Espanha", "Inglaterra", "França", "Portugal", "Holanda"],
    correct: 3,
  },
  {
    id: 26,
    subject: "Geografia - Energia",
    question: "A principal fonte de energia elétrica no Brasil é:",
    options: ["Termelétrica", "Nuclear", "Solar", "Hidrelétrica", "Eólica"],
    correct: 3,
  },
  {
    id: 27,
    subject: "História - Segunda Guerra",
    question: "A Segunda Guerra Mundial terminou em:",
    options: ["1918", "1939", "1945", "1950", "1960"],
    correct: 2,
  },
  {
    id: 28,
    subject: "Geografia - Globalização",
    question: "Globalização refere-se à:",
    options: [
      "Isolamento dos países",
      "Integração econômica mundial",
      "Crescimento populacional",
      "Preservação ambiental",
      "Nacionalização de empresas",
    ],
    correct: 1,
  },
  {
    id: 29,
    subject: "Filosofia - Ética",
    question: "Ética estuda:",
    options: ["O belo", "O conhecimento", "O bem e o mal", "A existência", "A lógica"],
    correct: 2,
  },
  {
    id: 30,
    subject: "Sociologia - Weber",
    question: "Para Weber, a ação social é orientada:",
    options: ["Por instintos", "Pelo comportamento de outros", "Por reflexos", "Por hábitos apenas", "Por genes"],
    correct: 1,
  },
  {
    id: 31,
    subject: "História - Império",
    question: "Dom Pedro II governou o Brasil por:",
    options: ["20 anos", "30 anos", "40 anos", "49 anos", "60 anos"],
    correct: 3,
  },
  {
    id: 32,
    subject: "Geografia - Clima",
    question: "El Niño é um fenômeno que afeta:",
    options: ["Apenas o Brasil", "O Oceano Atlântico", "O Oceano Pacífico", "Os rios brasileiros", "Apenas a Amazônia"],
    correct: 2,
  },
  {
    id: 33,
    subject: "Filosofia - Kant",
    question: "Para Kant, o imperativo categórico é:",
    options: [
      "Uma lei da natureza",
      "Um princípio moral universal",
      "Uma teoria científica",
      "Uma crença religiosa",
      "Um costume social",
    ],
    correct: 1,
  },
  {
    id: 34,
    subject: "Sociologia - Anomia",
    question: "Anomia, segundo Durkheim, é:",
    options: [
      "Excesso de regras",
      "Ausência de normas sociais",
      "Revolução social",
      "Solidariedade mecânica",
      "Consciência coletiva",
    ],
    correct: 1,
  },
  {
    id: 35,
    subject: "História - Absolutismo",
    question: "No absolutismo, o rei possuía poder:",
    options: ["Limitado", "Dividido", "Absoluto", "Democrático", "Inexistente"],
    correct: 2,
  },
  {
    id: 36,
    subject: "Geografia - Cartografia",
    question: "Latitude é medida:",
    options: [
      "Norte-Sul a partir da Linha do Equador",
      "Leste-Oeste a partir de Greenwich",
      "Em metros",
      "Em quilômetros",
      "Pela altitude",
    ],
    correct: 0,
  },
  {
    id: 37,
    subject: "História - Mercantilismo",
    question: "O mercantilismo caracterizava-se por:",
    options: [
      "Livre comércio",
      "Intervenção estatal na economia",
      "Socialismo",
      "Anarquismo econômico",
      "Economia de subsistência",
    ],
    correct: 1,
  },
  {
    id: 38,
    subject: "Geografia - Indústria",
    question: "A Revolução Industrial iniciou-se:",
    options: ["Na França", "Nos EUA", "Na Alemanha", "Na Inglaterra", "Na Itália"],
    correct: 3,
  },
  {
    id: 39,
    subject: "Filosofia - Existencialismo",
    question: "'A existência precede a essência' é ideia de:",
    options: ["Platão", "Descartes", "Sartre", "Hegel", "Kant"],
    correct: 2,
  },
  {
    id: 40,
    subject: "Sociologia - Mudança Social",
    question: "Mudança social pode ser causada por:",
    options: [
      "Apenas fatores econômicos",
      "Apenas fatores culturais",
      "Múltiplos fatores",
      "Apenas tecnologia",
      "Apenas política",
    ],
    correct: 2,
  },
  {
    id: 41,
    subject: "História - Renascimento",
    question: "O Renascimento valorizava:",
    options: ["O teocentrismo", "O antropocentrismo", "O feudalismo", "A Idade Média", "O absolutismo"],
    correct: 1,
  },
  {
    id: 42,
    subject: "Geografia - Recursos Naturais",
    question: "Recursos renováveis são aqueles que:",
    options: ["Nunca acabam", "Podem se regenerar", "São industrializados", "Vêm do petróleo", "São importados"],
    correct: 1,
  },
  {
    id: 43,
    subject: "História - Guerra Fria",
    question: "A Guerra Fria foi um conflito entre:",
    options: ["EUA e Inglaterra", "França e Alemanha", "EUA e URSS", "China e Japão", "Brasil e Argentina"],
    correct: 2,
  },
  {
    id: 44,
    subject: "Geografia - Blocos Econômicos",
    question: "O MERCOSUL é um bloco:",
    options: ["Europeu", "Asiático", "Sul-americano", "Africano", "Norte-americano"],
    correct: 2,
  },
  {
    id: 45,
    subject: "Filosofia - Política",
    question: "Maquiavel defendia que:",
    options: [
      "Os fins justificam os meios",
      "A ética deve guiar a política",
      "O rei deve ser justo",
      "A democracia é ideal",
      "O poder corrompe sempre",
    ],
    correct: 0,
  },
]

// 45 Questões de Ciências da Natureza
export const naturezaQuestions: Question[] = [
  {
    id: 1,
    subject: "Biologia - Células",
    question: "A mitocôndria é responsável por:",
    options: ["Fotossíntese", "Respiração celular", "Síntese de proteínas", "Divisão celular", "Digestão celular"],
    correct: 1,
  },
  {
    id: 2,
    subject: "Física - Cinemática",
    question: "A velocidade média é calculada por:",
    options: ["distância × tempo", "distância / tempo", "tempo / distância", "distância + tempo", "distância - tempo"],
    correct: 1,
  },
  {
    id: 3,
    subject: "Química - Tabela Periódica",
    question: "O elemento químico mais abundante no universo é:",
    options: ["Oxigênio", "Carbono", "Hidrogênio", "Nitrogênio", "Hélio"],
    correct: 2,
  },
  {
    id: 4,
    subject: "Biologia - Genética",
    question: "A molécula que carrega informação genética é:",
    options: ["RNA", "DNA", "Proteína", "Lipídio", "Carboidrato"],
    correct: 1,
  },
  {
    id: 5,
    subject: "Física - Leis de Newton",
    question: "A Primeira Lei de Newton trata de:",
    options: ["Ação e reação", "Inércia", "Gravitação", "Aceleração", "Energia"],
    correct: 1,
  },
  {
    id: 6,
    subject: "Química - Ligações",
    question: "A água (H₂O) possui ligação:",
    options: ["Iônica", "Metálica", "Covalente", "Van der Waals", "Ponte de hidrogênio"],
    correct: 2,
  },
  {
    id: 7,
    subject: "Biologia - Ecologia",
    question: "Produtores em uma cadeia alimentar são:",
    options: ["Carnívoros", "Herbívoros", "Plantas", "Fungos", "Bactérias decompositoras"],
    correct: 2,
  },
  {
    id: 8,
    subject: "Física - Energia",
    question: "Energia não pode ser:",
    options: ["Transformada", "Transferida", "Armazenada", "Criada ou destruída", "Medida"],
    correct: 3,
  },
  {
    id: 9,
    subject: "Química - pH",
    question: "Uma solução com pH 3 é:",
    options: ["Neutra", "Básica", "Ácida", "Salina", "Tampão"],
    correct: 2,
  },
  {
    id: 10,
    subject: "Biologia - Evolução",
    question: "A teoria da evolução foi proposta por:",
    options: ["Mendel", "Darwin", "Lamarck", "Watson", "Pasteur"],
    correct: 1,
  },
  {
    id: 11,
    subject: "Física - Óptica",
    question: "A luz se propaga:",
    options: ["Apenas no vácuo", "Apenas em meios materiais", "Em linha reta", "Em curvas sempre", "Apenas na água"],
    correct: 2,
  },
  {
    id: 12,
    subject: "Química - Estados Físicos",
    question: "A passagem de líquido para gasoso chama-se:",
    options: ["Fusão", "Solidificação", "Vaporização", "Condensação", "Sublimação"],
    correct: 2,
  },
  {
    id: 13,
    subject: "Biologia - Fotossíntese",
    question: "Na fotossíntese, as plantas produzem:",
    options: ["CO₂", "H₂O", "Glicose", "O₂ e Glicose", "Apenas O₂"],
    correct: 3,
  },
  {
    id: 14,
    subject: "Física - Eletricidade",
    question: "A unidade de corrente elétrica é:",
    options: ["Volt", "Ampere", "Ohm", "Watt", "Joule"],
    correct: 1,
  },
  {
    id: 15,
    subject: "Química - Reações",
    question: "Em uma reação de combustão, sempre há:",
    options: ["Formação de sal", "Liberação de O₂", "Consumo de O₂", "Formação de metal", "Absorção de luz"],
    correct: 2,
  },
  {
    id: 16,
    subject: "Biologia - Sistema Digestório",
    question: "A digestão de proteínas começa no:",
    options: ["Estômago", "Intestino", "Boca", "Esôfago", "Fígado"],
    correct: 0,
  },
  {
    id: 17,
    subject: "Física - Ondas",
    question: "O som é uma onda:",
    options: ["Eletromagnética", "Transversal", "Mecânica", "Luminosa", "Estacionária"],
    correct: 2,
  },
  {
    id: 18,
    subject: "Química - Orgânica",
    question: "Hidrocarbonetos contêm apenas:",
    options: ["C e O", "C e H", "H e O", "C, H e O", "C, H e N"],
    correct: 1,
  },
  {
    id: 19,
    subject: "Biologia - Vírus",
    question: "Vírus são considerados:",
    options: [
      "Células completas",
      "Bactérias pequenas",
      "Parasitas intracelulares obrigatórios",
      "Fungos microscópicos",
      "Protozoários",
    ],
    correct: 2,
  },
  {
    id: 20,
    subject: "Física - Termodinâmica",
    question: "A temperatura é uma medida de:",
    options: ["Energia total", "Agitação molecular", "Massa", "Volume", "Pressão"],
    correct: 1,
  },
  {
    id: 21,
    subject: "Química - Mol",
    question: "Um mol contém aproximadamente:",
    options: [
      "6 × 10²³ partículas",
      "6 × 10²² partículas",
      "6 × 10²⁴ partículas",
      "1000 partículas",
      "1 milhão de partículas",
    ],
    correct: 0,
  },
  {
    id: 22,
    subject: "Biologia - Respiração",
    question: "A troca gasosa nos pulmões ocorre nos:",
    options: ["Brônquios", "Bronquíolos", "Alvéolos", "Traqueia", "Faringe"],
    correct: 2,
  },
  {
    id: 23,
    subject: "Física - Gravitação",
    question: "A Lei da Gravitação Universal foi proposta por:",
    options: ["Einstein", "Galileu", "Newton", "Kepler", "Copérnico"],
    correct: 2,
  },
  {
    id: 24,
    subject: "Química - Ácidos",
    question: "O ácido clorídrico tem fórmula:",
    options: ["HCl", "H₂SO₄", "HNO₃", "H₃PO₄", "CH₃COOH"],
    correct: 0,
  },
  {
    id: 25,
    subject: "Biologia - Sistema Nervoso",
    question: "Os neurônios transmitem:",
    options: ["Sangue", "Hormônios", "Impulsos nervosos", "Oxigênio", "Nutrientes"],
    correct: 2,
  },
  {
    id: 26,
    subject: "Física - Magnetismo",
    question: "Polos magnéticos iguais:",
    options: ["Se atraem", "Se repelem", "Não interagem", "Se neutralizam", "Formam ímã"],
    correct: 1,
  },
  {
    id: 27,
    subject: "Química - Bases",
    question: "O hidróxido de sódio (NaOH) é:",
    options: ["Ácido", "Base", "Sal", "Óxido", "Neutro"],
    correct: 1,
  },
  {
    id: 28,
    subject: "Biologia - Mendel",
    question: "A Lei da Segregação foi proposta por:",
    options: ["Darwin", "Mendel", "Watson", "Lamarck", "Pasteur"],
    correct: 1,
  },
  {
    id: 29,
    subject: "Física - Pressão",
    question: "A pressão atmosférica ao nível do mar é aproximadamente:",
    options: ["1 atm", "10 atm", "0,1 atm", "100 atm", "0,01 atm"],
    correct: 0,
  },
  {
    id: 30,
    subject: "Química - Radioatividade",
    question: "Partículas alfa são compostas por:",
    options: ["Elétrons", "Prótons", "Nêutrons", "Núcleos de hélio", "Fótons"],
    correct: 3,
  },
  {
    id: 31,
    subject: "Biologia - Sangue",
    question: "As hemácias transportam:",
    options: ["Anticorpos", "Oxigênio", "Hormônios", "Nutrientes", "Apenas CO₂"],
    correct: 1,
  },
  {
    id: 32,
    subject: "Física - Trabalho",
    question: "Trabalho é o produto de:",
    options: [
      "Força × velocidade",
      "Força × deslocamento",
      "Massa × aceleração",
      "Energia × tempo",
      "Potência × tempo",
    ],
    correct: 1,
  },
  {
    id: 33,
    subject: "Química - Pilhas",
    question: "Em uma pilha, ocorre transformação de energia:",
    options: [
      "Térmica em elétrica",
      "Química em elétrica",
      "Elétrica em térmica",
      "Mecânica em elétrica",
      "Luminosa em elétrica",
    ],
    correct: 1,
  },
  {
    id: 34,
    subject: "Biologia - Hormônios",
    question: "A insulina é produzida pelo:",
    options: ["Fígado", "Pâncreas", "Estômago", "Rim", "Coração"],
    correct: 1,
  },
  {
    id: 35,
    subject: "Física - Relatividade",
    question: "A Teoria da Relatividade foi proposta por:",
    options: ["Newton", "Maxwell", "Einstein", "Planck", "Bohr"],
    correct: 2,
  },
  {
    id: 36,
    subject: "Química - Sais",
    question: "O cloreto de sódio (NaCl) é:",
    options: ["Ácido", "Base", "Sal", "Óxido", "Peróxido"],
    correct: 2,
  },
  {
    id: 37,
    subject: "Biologia - Ciclos",
    question: "O ciclo da água envolve:",
    options: [
      "Apenas evaporação",
      "Evaporação, condensação e precipitação",
      "Apenas chuva",
      "Apenas rios",
      "Apenas oceanos",
    ],
    correct: 1,
  },
  {
    id: 38,
    subject: "Física - Potência",
    question: "A unidade de potência é:",
    options: ["Joule", "Watt", "Newton", "Pascal", "Hertz"],
    correct: 1,
  },
  {
    id: 39,
    subject: "Química - Eletrólise",
    question: "Na eletrólise, a energia elétrica produz:",
    options: ["Reação química", "Apenas calor", "Luz", "Som", "Movimento"],
    correct: 0,
  },
  {
    id: 40,
    subject: "Biologia - Taxonomia",
    question: "A menor unidade taxonômica é:",
    options: ["Reino", "Filo", "Classe", "Gênero", "Espécie"],
    correct: 4,
  },
  {
    id: 41,
    subject: "Física - Refração",
    question: "A refração ocorre quando a luz:",
    options: ["É absorvida", "Muda de meio", "É refletida", "Para de se propagar", "Aumenta de intensidade"],
    correct: 1,
  },
  {
    id: 42,
    subject: "Química - Catalisadores",
    question: "Um catalisador:",
    options: [
      "Aumenta a temperatura",
      "Acelera a reação",
      "É consumido na reação",
      "Impede a reação",
      "Cria novos produtos",
    ],
    correct: 1,
  },
  {
    id: 43,
    subject: "Biologia - Membrana",
    question: "A membrana plasmática é:",
    options: ["Totalmente permeável", "Impermeável", "Semipermeável", "Rígida", "Ausente em células"],
    correct: 2,
  },
  {
    id: 44,
    subject: "Física - Densidade",
    question: "Densidade é a razão entre:",
    options: ["Massa e volume", "Força e área", "Trabalho e tempo", "Velocidade e tempo", "Energia e massa"],
    correct: 0,
  },
  {
    id: 45,
    subject: "Química - Isomeria",
    question: "Isômeros são compostos com:",
    options: [
      "Mesma fórmula molecular, estruturas diferentes",
      "Fórmulas diferentes",
      "Mesmos átomos em mesma ordem",
      "Massas diferentes",
      "Elementos diferentes",
    ],
    correct: 0,
  },
]

// Função para embaralhar questões
export function shuffleQuestions(questions: Question[]): Question[] {
  const shuffled = [...questions]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

// Função para selecionar questões dinâmicas por dia e matéria
export function getQuestionsForExam(day: number, subject: string): Question[] {
  // Seed baseada no dia para consistência, mas diferença entre dias
  const seed = day * 1000

  let allQuestions: Question[] = []

  // Dia 1: Linguagens (45) + Humanas (45) = 90 questões
  // Dia 2: Matemática (45) + Natureza (45) = 90 questões
  if (day === 1) {
    allQuestions = [...linguagensQuestions, ...humanasQuestions]
  } else {
    allQuestions = [...matematicaQuestions, ...naturezaQuestions]
  }

  // Embaralha com seed determinística mas diferente por dia
  const shuffled = allQuestions
    .map((q, index) => ({ q, sort: Math.sin(seed + index) }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ q }) => q)

  // Se uma matéria específica foi pedida, filtra
  if (subject === "linguagens") {
    return shuffleQuestions(linguagensQuestions)
  } else if (subject === "matematica") {
    return shuffleQuestions(matematicaQuestions)
  } else if (subject === "humanas") {
    return shuffleQuestions(humanasQuestions)
  } else if (subject === "natureza") {
    return shuffleQuestions(naturezaQuestions)
  }

  return shuffled
}
